name: Ansible Linter
on: [push]
jobs:
  Ansible-Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: |
          apt update 
          apt install ansible-lint
      - run: |
          cd ansible
          find . -name "*.y*ml" | xargs -r ansible-lint --force-color

